#!/bin/bash

if [ -z "$1" ]
then
	name="hello"
else
	name=$1
fi

wla-gb -x -o $name.o $name.asm &&
wlalink -d -v -s linkfile $name.gb &&
dd if=$name.gb of=$name.bin bs=1 skip=50646 count=196 &&
hexdump $name.bin
